/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#f9f9ff",
        "on-secondary-container": "#5c647a",
        "background": "#f9f9ff",
        "on-tertiary-fixed": "#001f26",
        "secondary-container": "#dae2fd",
        "on-surface": "#151c27",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#4cd7f6",
        "primary-container": "#4f46e5",
        "inverse-on-surface": "#ebf1ff",
        "surface-container-highest": "#dce2f3",
        "tertiary": "#00505f",
        "on-tertiary-fixed-variant": "#004e5c",
        "inverse-primary": "#c3c0ff",
        "error": "#ba1a1a",
        "on-surface-variant": "#464555",
        "on-primary-container": "#dad7ff",
        "inverse-surface": "#2a313d",
        "surface-container-high": "#e2e8f8",
        "surface-bright": "#f9f9ff",
        "on-secondary-fixed-variant": "#3f465c",
        "surface-variant": "#dce2f3",
        "primary-fixed-dim": "#c3c0ff",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#acedff",
        "on-secondary": "#ffffff",
        "outline-variant": "#c7c4d8",
        "secondary-fixed": "#dae2fd",
        "on-error": "#ffffff",
        "surface-dim": "#d3daea",
        "on-primary-fixed": "#0f0069",
        "primary-fixed": "#e2dfff",
        "tertiary-container": "#006a7c",
        "on-background": "#151c27",
        "secondary": "#565e74",
        "on-primary": "#ffffff",
        "surface-container": "#e7eefe",
        "on-secondary-fixed": "#131b2e",
        "surface-tint": "#4d44e3",
        "on-primary-fixed-variant": "#3323cc",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#93e8ff",
        "secondary-fixed-dim": "#bec6e0",
        "outline": "#777587",
        "error-container": "#ffdad6",
        "primary": "#3525cd",
        "surface-container-low": "#f0f3ff",
        // Keep brand for backward compatibility where needed
        brand: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#0c4a6e',
          950: '#082f49',
        },
      },
      spacing: {
        "lg": "24px",
        "xl": "32px",
        "sm": "8px",
        "md": "16px",
        "base": "4px",
        "max-width": "1280px",
        "xxl": "48px",
        "gutter": "24px",
        "xs": "4px"
      },
      fontFamily: {
        "label-caps": ["Inter"],
        "body-md": ["Inter"],
        "h3": ["Inter"],
        "h2": ["Inter"],
        "h1": ["Inter"],
        "body-lg": ["Inter"],
        "body-sm": ["Inter"],
        "code-md": ["monospace"]
      },
      fontSize: {
        "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "h3": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "h2": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "h1": ["36px", {"lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "code-md": ["14px", {"lineHeight": "22px", "fontWeight": "400"}]
      },
      animation: {
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
    },
  },
  plugins: [],
}
